### ISSUE TITLE
VS Gallery and CI Build download links are broken in the read me.

### ISSUE THREAD

**Issue by AsifMushtaq** [alhardy/aspnet-kickstart#1]

**Comment by alhardy** [comment]
Waiting for the .NET Core intial RTM before releasing

**Comment by alhardy** [comment]
@AsifMushtaq alpha version released, the build and vsix links have been updated.

Note: a release has only been pushed to the Open vsix gallery for testing.

http://vsixgallery.com/extension/F9BA239C-2420-4167-A986-3C11670DB3E0/
